name: Earthly CI/CD

on:
  schedule:
    - cron: "38 20 * * *"
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        type:
          - spigot
          - paper
          - vanilla
        version:
          - latest
          - 1.20.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - name: Build, test, and push image
        run: earthly --allow-privileged --use-inline-cache --save-inline-cache --push +ci.${{ matrix.type }} --version=${{ matrix.version }}
